import Head from "next/head";
import Feed from "../components/Feed";
import Header from "../components/Header";

export default function Home() {
    return (
        <div className="">
            <Head>
                <title>Instagram Clone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Header />

            <Feed />
        </div>
    );
}
